Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'

Style/IfUnlessModifier:
  Enabled: false

Style/DotPosition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

SignalException:
  Enabled: false
